project:
  name: Ghost Docker
domains:
  - https://tquizzle.github.io/clamav-alpine/
repos:
  - url: https://github.com/tquizzle/clamav-alpine.git
    branch: master
    description: ClamAV Docker image based on Alpine Linux
