name: Deploy docmd docs to GitHub Pages

on:
  push:
    branches: ["main"]  # Your default branch
  workflow_dispatch:   # Allows manual workflow trigger from Actions tab

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install docmd (globally or from devDependencies)
        run: npm install -g @mgks/docmd

      - name: Build site with docmd
        run: docmd build # Assumes config.js is in the root and correctly points to srcDir/outputDir

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site # This should be your outputDir path

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
